### ISSUE TITLE
Fails to connect after Tailscale key expiry

### ISSUE THREAD

**Issue by tom-a-horrocks** [darkrain42/tailscale-initramfs#5]
Thanks for making this. I've found that when the Tailscale auth key expires then the machine fails to connect to the tailnet with error `backend error: invalid key: API key <xxx> not valid`. This is despite the machine already being authenticated on the tailnet **with node key expiry disabled**. I would have thought the auth key was only needed on the first connection -- am I missing something? Otherwise a new auth key has to be made every 90 days (the max expiry time).

**Comment by darkrain42** [comment]
The initramfs registers as a different client into your tailnet from the device itself when fully booted.  For instance, I have a system named 'elan', but when it's booted into the initramfs, 'elan' shows up as offline, and there's a separate tagged device named 'elan-initramfs'.

And yes, this does requires a non-expired auth key at the time the initramfs executes.  I have a recurring calendar reminder that goes off every 70 days or so to rotate the keys and update the initramfs's on my systems (more accurately, I update it in my ansible, and then have that push the update out to all the systems).

I should probably do a better job of spelling this out in the README.

https://github.com/lugoues/tailscale-initramfs may behave more like what you're looking for -- as I understand it (when I was looking at what they had done), you register a permanent 'initrd' instance of the device in your tailnet when setting up the package, and it will remain there all the time (but only be online when booted into the initramfs). You can then disable node key expiry for that machine, and not need to worry about doing extra work every 90 days.

**Comment by tom-a-horrocks** [comment]
Okay, that makes sense and thank you for clearing that up. Something like this before the Install section would have helped me:

> **Caution:** initramfs cannot connect to your tailnet if the auth key is expired, even if the node key expiry is disabled in Tailscale's admin dashboard. This will render you unable to unlock your encrypted system over your tailnet. If you cannot unlock your system via more traditional means, i.e. over the LAN or physically (if the password hasn't been disabled), then you will be permanently locked out of your system. To avoid this, make sure you create a new key before the old one expires and update initramfs accordingly (i.e. rotate your keys). The maximum auth key life is 90 days.

_Edit: I didn't actually get permanently locked out of my system, just thought it could happen to someone else!_
